CREATE ROLE mentora_app LOGIN PASSWORD 'mentora_dev_only'
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT ALL PRIVILEGES ON DATABASE mentora TO mentora_app;
GRANT USAGE, CREATE ON SCHEMA public TO mentora_app;
